package com.renx86.gdlapp.data

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import java.io.File

/**
 * Converts raw Android WebView cookies into a Netscape HTTP Cookie File
 * that gallery-dl can read. Also supports manual paste of cookie text.
 *
 * Netscape format (7 tab-separated columns per line):
 *   domain  flag  path  secure  expiration  name  value
 *
 * Example:
 *   .twitter.com	TRUE	/	TRUE	2147483647	auth_token	abc123
 */
object CookieExporter {

    private const val HEADER = "# Netscape HTTP Cookie File\n" +
            "# https://curl.se/rfc/cookie_spec.html\n" +
            "# This file was generated by GDL Android! Edit at your own risk.\n\n"

    /**
     * Extracts cookies from Android's CookieManager for the given URL,
     * converts them to Netscape format, and writes them to the given file.
     *
     * @param url The URL the user logged into (e.g. "https://twitter.com")
     * @param outputFile Where to write the cookies.txt
     * @return true if cookies were successfully exported
     */
    fun exportFromWebView(url: String, outputFile: File): Boolean {
        val cookieManager = CookieManager.getInstance()
        cookieManager.flush() // CRITICAL: commit in-memory cookies to storage

        val rawCookies = cookieManager.getCookie(url) ?: return false
        if (rawCookies.isBlank()) return false

        val domain = extractDomain(url)
        val isSecure = url.startsWith("https")
        val netscapeLines = convertToNetscape(rawCookies, domain, isSecure)

        outputFile.parentFile?.mkdirs()
        outputFile.writeText(HEADER + netscapeLines)
        return true
    }

    /**
     * Takes manually pasted Netscape cookie text, validates it has the header,
     * and writes it to the given file.
     *
     * @param pastedText Raw Netscape-format cookie text from the user
     * @param outputFile Where to write the cookies.txt
     * @return true if the text was valid and written
     */
    fun exportFromPaste(pastedText: String, outputFile: File): Boolean {
        val trimmed = pastedText.trim()
        if (trimmed.isEmpty()) return false

        // If the user didn't include the header, add it
        val content = if (trimmed.startsWith("#")) {
            trimmed
        } else {
            HEADER + trimmed
        }

        // Basic validation: each non-comment, non-empty line should have 7 tab-separated fields
        val dataLines = content.lines().filter { it.isNotBlank() && !it.startsWith("#") }
        if (dataLines.isEmpty()) return false
        val allValid = dataLines.all { line -> line.split("\t").size == 7 }
        if (!allValid) return false

        outputFile.parentFile?.mkdirs()
        outputFile.writeText(content)
        return true
    }

    /**
     * Converts a raw cookie string like "SID=xxx; HSID=yyy; auth=zzz"
     * into Netscape format lines.
     */
    private fun convertToNetscape(rawCookies: String, domain: String, isSecure: Boolean): String {
        val dotDomain = if (domain.startsWith(".")) domain else ".$domain"
        val flag = "TRUE" // subdomain matching
        val path = "/"
        val secure = if (isSecure) "TRUE" else "FALSE"
        val expiration = "2147483647" // Unix max (year 2038) — we don't know actual expiry

        return rawCookies.split("; ").joinToString("\n") { cookie ->
            val parts = cookie.split("=", limit = 2)
            if (parts.size == 2) {
                val name = parts[0].trim()
                val value = parts[1].trim()
                "$dotDomain\t$flag\t$path\t$secure\t$expiration\t$name\t$value"
            } else {
                "" // Skip malformed cookies
            }
        }.lines().filter { it.isNotBlank() }.joinToString("\n")
    }

    /**
     * Extracts the base domain from a URL.
     * "https://www.twitter.com/login" → "twitter.com"
     */
    private fun extractDomain(url: String): String {
        return try {
            val host = Uri.parse(url).host ?: url
            // Remove "www." prefix if present
            host.removePrefix("www.")
        } catch (e: Exception) {
            url
        }
    }
}
